lambda: fail if the function fails, improve debugging (#373)
Previously if deploying failed it would proceed to invoke, and fail
there just saying "function is Failed"

With this change we get a better experience when the image is invalid:

```
=== RUN   TestAccTestsResource_Lambda
    tests_lambda_resource_test.go:26: Step 1/1 error: Error running apply: exit status 1
        
        Error: test failed
        
          with imagetest_tests_lambda.foo,
          on terraform_plugin_test.tf line 11, in resource "imagetest_tests_lambda" "foo":
          11: resource "imagetest_tests_lambda" "foo" {
        
        function failed: MissingParentDirectory: Parent directory does not exist for
        file: function/snapshot_restore_py-1.0.0.dist-info/RECORD
```

---------

Signed-off-by: Jason Hall <jason@chainguard.dev>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>